# OpenShift Deployment Configuration for E.E.L. Application Portal
# Deploy with: oc apply -f openshift-deploy.yaml

apiVersion: v1
kind: List
items:

# Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: eel-website
    labels:
      app: eel-website
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: eel-website
    template:
      metadata:
        labels:
          app: eel-website
      spec:
        imagePullSecrets:
        - name: ghcr-pull-secret
        containers:
        - name: eel-website
          image: ghcr.io/williethewhale/eel-website:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: PORT
            value: "8080"
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eel-secrets
                key: admin-password
          - name: EMAIL_USER
            valueFrom:
              secretKeyRef:
                name: eel-secrets
                key: email-user
                optional: true
          - name: EMAIL_PASS
            valueFrom:
              secretKeyRef:
                name: eel-secrets
                key: email-pass
                optional: true
          - name: NOTIFY_EMAIL
            value: "wilk05@unc.edu"
          - name: SMTP_HOST
            valueFrom:
              secretKeyRef:
                name: eel-secrets
                key: smtp-host
                optional: true
          - name: SMTP_PORT
            valueFrom:
              secretKeyRef:
                name: eel-secrets
                key: smtp-port
                optional: true
          - name: SMTP_FROM
            value: "wilk05@unc.edu"
          - name: SITE_URL
            value: "https://eel-website.apps.cloudapps.unc.edu"
          volumeMounts:
          - name: data-volume
            mountPath: /app/backend/data
          - name: uploads-volume
            mountPath: /app/backend/uploads
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
        volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: eel-data-pvc
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: eel-uploads-pvc

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: eel-website
    labels:
      app: eel-website
  spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    selector:
      app: eel-website

# Route (external access)
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: eel-website
    labels:
      app: eel-website
  spec:
    to:
      kind: Service
      name: eel-website
    port:
      targetPort: 8080
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

# Persistent Volume Claims
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: eel-data-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: eel-uploads-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi

---
# Setup instructions:
#
# 1. Create application secrets:
#
#    For UNC relay (relay.unc.edu, no email creds needed):
# oc create secret generic eel-secrets \
#   --from-literal=admin-password='your-secure-password' \
#   --from-literal=smtp-host='relay.unc.edu' \
#   --from-literal=smtp-port='587'
#
#    For Gmail SMTP (local dev / non-UNC):
# oc create secret generic eel-secrets \
#   --from-literal=admin-password='your-secure-password' \
#   --from-literal=email-user='your-email@gmail.com' \
#   --from-literal=email-pass='your-app-password'
#
# 2. Create GHCR pull secret (for pulling images from GitHub Container Registry):
# oc create secret docker-registry ghcr-pull-secret \
#   --docker-server=ghcr.io \
#   --docker-username=YOUR_GITHUB_USERNAME \
#   --docker-password=YOUR_GITHUB_PAT \
#   --docker-email=your-email@example.com
#
# 3. GitHub Actions secrets required:
#   OPENSHIFT_SERVER    - Your OpenShift cluster API URL (e.g., https://api.your-cluster.openshiftapps.com:6443)
#   OPENSHIFT_TOKEN     - Service account token (oc sa get-token deployer)
#   OPENSHIFT_NAMESPACE - Target namespace/project name
#
# 4. To force a redeployment with the latest image:
# oc rollout restart deployment/eel-website
